#!/usr/bin/env sh
echo "=============="
echo $@
echo "=============="
# rosbag play --bags=$1 --clock -r $2 $3 --skip-empty=0.5 --pause
rosbag play $@ --clock --skip-empty=0.5 -d 2 --pause #-s 2655
# rosbag play $@ --clock --skip-empty=0.5 --pause -r 1 #-s 2655
# rosbag play $@ --clock --skip-empty=0.5 --pause -r 1 #-s 2655